In [5]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from tabulate import tabulate
from itertools import combinations
import os
import warnings

# Suppress warnings
warnings.filterwarnings("ignore")

# Load data from Excel file
file_path = "SurveyData.xlsx"  # Update with actual path
xls = pd.ExcelFile(file_path)
first_sheet_name = xls.sheet_names[0]  # Get the first sheet name
survey_main = pd.read_excel(xls, sheet_name=first_sheet_name)

# Cleaning column names
def clean_column_names(df):
    df.columns = df.columns.str.lower().str.replace(" ", "_")
    return df

survey_main = clean_column_names(survey_main)

# Create output directory if not exists
output_dir = "media"
os.makedirs(output_dir, exist_ok=True)

# Display Summary Statistics
print("\nSummary Statistics:")
print(tabulate(survey_main.describe(), headers='keys', tablefmt='pretty'))

# Frequency Tables for Categorical Variables
categorical_vars = ["gender", "marital_status", "education", "religion", "subcaste", 
                    "income_sources", "bpl_status", "ration_card", "loan_status"]

for var in categorical_vars:
    print(f"\nFrequency Table for {var}:")
    freq_table = survey_main[var].value_counts(dropna=False).reset_index()
    freq_table.columns = [var, "Count"]
    print(tabulate(freq_table, headers='keys', tablefmt='pretty'))
    
    # Bar plot visualization
    plt.figure(figsize=(8, 4))
    sns.barplot(x=freq_table[var], y=freq_table["Count"], palette="viridis")
    plt.xticks(rotation=45)
    plt.title(f"Frequency of {var}")
    plt.xlabel(var)
    plt.ylabel("Count")
    plt.savefig(os.path.join(output_dir, f"Frequency_of_{var}.jpg"))
    plt.close()

Summary Statistics:
+-------+--------------------+--------------------+--------------------+----------------------+----------------------------+-----------------------+--------------------+-------------------------+---------------------------+------------------------------+------------------------+----------------------+-------------------+--------------------+---------------------+---------------------+---------------------+------------------------+-------------------------+-------------------------+-------------------+------------------------------+-------------------+--------------------+---------------------+---------------------+--------------------+--------------------+--------------------+--------------------+---------------------+--------------------+---------------------+--------------------+--------+--------------------+-------------+---------------------+------------+---------------------+---------------------+----------------------+--------------------+--------------------+----------------------+---------------------+---------------------+---------------------+-----------------------+---------------------+-----------------------+----------------------------+----------------------+---------------------------------+------------------------------------+------------------------+-----------------------------+------------------------------+-------------------------------------+---------------------+---------------------+----------------------------+-------------------------+-------------------------------+-----------------------------+--------------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+---------------------+--------------------+----------------------------------------------+---------------------------------+------------------------------+-----------------------------------+-------------------------+-----------------------+----------------------------------------+----------------------------------------+----------------------------------------+---------------------------+--------------------+--------------+-------+----------------+----------------+------------------+--------------+--------------------+--------------------+--------------------+-------------------------+----------------------+-------------------+-------+------------+------------------+-----------------+-----------------------+-----------------+--------------+--------------------+------------------------+------------------------+-----------------------------+-------------------+--------------------+---------------------------+--------------------------------+---------------------------+-------------------------+-------+--------------+-------------------+---------------------------------+----------------------------+---------------------------------------+---------------------------------+-------------------------+-------+----------------------+----------+-------------------+--------------------+---------------+--------------------+---------------------+--------------------+--------------------+---------------------+-------------------+-------------------------------+--------+---------------+-------+-------------------+
|       |        srno        |        year        |        age         | total_family_members | income_sources/agriculture | income_sources/labour | income_sources/job | income_sources/business | income_sources/privatejob | income_sources/governmentjob | income_sources/pension | income_sources/other |  soiltestedyear   | water_sources/none | water_sources/river | water_sources/well  | water_sources/canal | water_sources/borewell | water_sources/farm_pond | water_sources/reservoir | water_sources/dam | water_sources/neighbor_water |      cotton       |       maize        |        jowar        |        bajra        |       pulses       |      soybean       |       wheat        |        gram        |       sorghum       |       maize2       |      groundnut      |       melon        | sesame |       banana       | pomegranate |       citrus        | vegetables |      bullocks       |         cow         |       poultry        |      sprayer       |       motor        |       thresher       |       tractor       | business_type/labor | business_type/dairy | business_type/poultry |  business_type/job  | business_type/cottage | business_type/goat_farming | business_type/other  | loan_purpose/agriculture_inputs | loan_purpose/agriculture_machinery | loan_purpose/crop_loss | loan_purpose/debt_repayment | loan_purpose/household_needs | loan_purpose/supplementary_business | loan_purpose/other  |  loan_source/bank   | loan_source/private_lender | loan_source/cooperative | loan_source/relatives_friends | loan_source/self_help_group | loan_source/microfinance | loan_source/other  |   loan_duration    |  overdue_duration  |   difficulties/1   |   difficulties/2   |   difficulties/3   |   difficulties/4    |   difficulties/5   | scheme_info_sources/local_agriculture_office | scheme_info_sources/cooperative | scheme_info_sources/tv_radio | scheme_info_sources/internet_apps | scheme_info_sources/ngo | scheme_info_sources/_ | scheme_improvements/more_info_training | scheme_improvements/simplified_process | scheme_improvements/local_help_centers | scheme_improvements/other | other_improvements | text_ye0iz81 | __005 | life_insurance | agri_insurance | cropping_pattern | crops_kharif | crops_kharif/jowar | crops_kharif/bajra | crops_kharif/maize | crops_kharif/urad_moong | crops_kharif/soybean | crops_kharif/____ | __008 | crops_rabi | crops_rabi/wheat | crops_rabi/gram | crops_rabi/jowar_late | crops_rabi/____ | crops_summer | crops_summer/maize | crops_summer/sugarcane | crops_summer/groundnut | crops_summer/cucumber_melon | crops_summer/____ | crops_horticulture | crops_horticulture/banana | crops_horticulture/pomegranate | crops_horticulture/citrus | crops_horticulture/____ | other | text_lo1xd85 | health_conditions | health_conditions/heart_disease | health_conditions/diabetes | health_conditions/respiratory_disease | health_conditions/mental_stress | health_conditions/other | __015 | other_farming_issues | job_card | balasaheb_project | ahilyadevi_nursery | other_schemes |      __002/1       |       __002/2       |      __002/3       |      __002/4       |       __002/5       |        _id        |       _submission_time        | _notes | _submitted_by | _tags |      _index       |
+-------+--------------------+--------------------+--------------------+----------------------+----------------------------+-----------------------+--------------------+-------------------------+---------------------------+------------------------------+------------------------+----------------------+-------------------+--------------------+---------------------+---------------------+---------------------+------------------------+-------------------------+-------------------------+-------------------+------------------------------+-------------------+--------------------+---------------------+---------------------+--------------------+--------------------+--------------------+--------------------+---------------------+--------------------+---------------------+--------------------+--------+--------------------+-------------+---------------------+------------+---------------------+---------------------+----------------------+--------------------+--------------------+----------------------+---------------------+---------------------+---------------------+-----------------------+---------------------+-----------------------+----------------------------+----------------------+---------------------------------+------------------------------------+------------------------+-----------------------------+------------------------------+-------------------------------------+---------------------+---------------------+----------------------------+-------------------------+-------------------------------+-----------------------------+--------------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+---------------------+--------------------+----------------------------------------------+---------------------------------+------------------------------+-----------------------------------+-------------------------+-----------------------+----------------------------------------+----------------------------------------+----------------------------------------+---------------------------+--------------------+--------------+-------+----------------+----------------+------------------+--------------+--------------------+--------------------+--------------------+-------------------------+----------------------+-------------------+-------+------------+------------------+-----------------+-----------------------+-----------------+--------------+--------------------+------------------------+------------------------+-----------------------------+-------------------+--------------------+---------------------------+--------------------------------+---------------------------+-------------------------+-------+--------------+-------------------+---------------------------------+----------------------------+---------------------------------------+---------------------------------+-------------------------+-------+----------------------+----------+-------------------+--------------------+---------------+--------------------+---------------------+--------------------+--------------------+---------------------+-------------------+-------------------------------+--------+---------------+-------+-------------------+
| count |       302.0        |       302.0        |       303.0        |        303.0         |           303.0            |         303.0         |       157.0        |          303.0          |           303.0           |            303.0             |         303.0          |        303.0         |        8.0        |       303.0        |        303.0        |        303.0        |        303.0        |         303.0          |          303.0          |          303.0          |       303.0       |            303.0             |       254.0       |       114.0        |        66.0         |        57.0         |        57.0        |        53.0        |        77.0        |        81.0        |        53.0         |        82.0        |        44.0         |        45.0        |  43.0  |        48.0        |    42.0     |        43.0         |    43.0    |        303.0        |        303.0        |        303.0         |       303.0        |       303.0        |        303.0         |        303.0        |        303.0        |        303.0        |         303.0         |        303.0        |         303.0         |           303.0            |        303.0         |              267.0              |               267.0                |         267.0          |            267.0            |            267.0             |                267.0                |        267.0        |        267.0        |           267.0            |          267.0          |             267.0             |            267.0            |          267.0           |       267.0        |       267.0        |       267.0        |       246.0        |       246.0        |       246.0        |        246.0        |       246.0        |                    303.0                     |              303.0              |            303.0             |               303.0               |          303.0          |         303.0         |                 303.0                  |                 303.0                  |                 303.0                  |           303.0           |        0.0         |     0.0      |  0.0  |      0.0       |      0.0       |       0.0        |     0.0      |        0.0         |        0.0         |        0.0         |           0.0           |         0.0          |        0.0        |  1.0  |    0.0     |       0.0        |       0.0       |          0.0          |       0.0       |     0.0      |        0.0         |          0.0           |          0.0           |             0.0             |        0.0        |        0.0         |            0.0            |              0.0               |            0.0            |           0.0           |  0.0  |     0.0      |        0.0        |               0.0               |            0.0             |                  0.0                  |               0.0               |           0.0           |  0.0  |         0.0          |   0.0    |        0.0        |        0.0         |      0.0      |        54.0        |        54.0         |        54.0        |        54.0        |        54.0         |       303.0       |              303              |  0.0   |      0.0      |  0.0  |       303.0       |
| mean  | 154.41390728476821 | 2022.8476821192053 | 44.557755775577554 |  4.726072607260726   |     0.9273927392739274     |  0.7491749174917491   |        0.0         |  0.013201320132013201   |   0.056105610561056105    |     0.013201320132013201     |  0.006600660066006601  | 0.026402640264026403 |        6.0        | 0.5115511551155115 | 0.0165016501650165  | 0.36303630363036304 | 0.0165016501650165  |  0.08250825082508251   |           0.0           |  0.0033003300330033004  |        0.0        |      0.0462046204620462      | 3.748031496062992 | 1.9298245614035088 | 0.48484848484848486 | 0.19298245614035087 | 0.3333333333333333 | 0.1320754716981132 | 1.7402597402597402 | 1.5432098765432098 | 0.41509433962264153 | 2.158536585365854  | 0.13636363636363635 | 0.2222222222222222 |  0.0   |       0.375        |     0.0     | 0.06976744186046512 |    0.0     | 0.18811881188118812 | 0.19801980198019803 | 0.019801980198019802 | 0.1617161716171617 | 0.2145214521452145 | 0.026402640264026403 | 0.07260726072607261 | 0.8943894389438944  | 0.0429042904290429  | 0.0033003300330033004 | 0.0165016501650165  |          0.0          |    0.009900990099009901    | 0.056105610561056105 |       0.8838951310861424        |        0.13857677902621723         |  0.47191011235955055   |     0.5056179775280899      |      0.6179775280898876      |         0.02247191011235955         | 0.02247191011235955 | 0.5393258426966292  |    0.25842696629213485     |   0.26217228464419473   |      0.3333333333333333       |     0.18352059925093633     |   0.06741573033707865    | 0.0149812734082397 |  463.063670411985  | 249.51685393258427 | 0.573170731707317  | 0.7764227642276422 | 0.5528455284552846 | 0.07723577235772358 | 0.0975609756097561 |             0.27722772277227725              |       0.11221122112211221       |     0.44224422442244227      |        0.7260726072607261         |   0.5841584158415841    |  0.0429042904290429   |           0.759075907590759            |           0.8514851485148515           |           0.7128712871287128           |            0.0            |        nan         |     nan      |  nan  |      nan       |      nan       |       nan        |     nan      |        nan         |        nan         |        nan         |           nan           |         nan          |        nan        |  2.0  |    nan     |       nan        |       nan       |          nan          |       nan       |     nan      |        nan         |          nan           |          nan           |             nan             |        nan        |        nan         |            nan            |              nan               |            nan            |           nan           |  nan  |     nan      |        nan        |               nan               |            nan             |                  nan                  |               nan               |           nan           |  nan  |         nan          |   nan    |        nan        |        nan         |      nan      | 0.5555555555555556 | 0.7407407407407407  | 0.6296296296296297 | 0.1111111111111111 | 0.07407407407407407 | 449930925.3432343 | 2025-03-09 12:40:22.412541184 |  nan   |      nan      |  nan  |       152.0       |
|  min  |        1.0         |       2022.0       |        5.0         |         1.0          |            0.0             |          0.0          |        0.0         |           0.0           |            0.0            |             0.0              |          0.0           |         0.0          |        2.0        |        0.0         |         0.0         |         0.0         |         0.0         |          0.0           |           0.0           |           0.0           |        0.0        |             0.0              |        0.0        |        0.0         |         0.0         |         0.0         |        0.0         |        0.0         |        0.0         |        0.0         |         0.0         |        0.0         |         0.0         |        0.0         |  0.0   |        0.0         |     0.0     |         0.0         |    0.0     |         0.0         |         0.0         |         0.0          |        0.0         |        0.0         |         0.0          |         0.0         |         0.0         |         0.0         |          0.0          |         0.0         |          0.0          |            0.0             |         0.0          |               0.0               |                0.0                 |          0.0           |             0.0             |             0.0              |                 0.0                 |         0.0         |         0.0         |            0.0             |           0.0           |              0.0              |             0.0             |           0.0            |        0.0         |        -1.0        |        -1.0        |        0.0         |        0.0         |        0.0         |         0.0         |        0.0         |                     0.0                      |               0.0               |             0.0              |                0.0                |           0.0           |          0.0          |                  0.0                   |                  0.0                   |                  0.0                   |            0.0            |        nan         |     nan      |  nan  |      nan       |      nan       |       nan        |     nan      |        nan         |        nan         |        nan         |           nan           |         nan          |        nan        |  2.0  |    nan     |       nan        |       nan       |          nan          |       nan       |     nan      |        nan         |          nan           |          nan           |             nan             |        nan        |        nan         |            nan            |              nan               |            nan            |           nan           |  nan  |     nan      |        nan        |               nan               |            nan             |                  nan                  |               nan               |           nan           |  nan  |         nan          |   nan    |        nan        |        nan         |      nan      |        0.0         |         0.0         |        0.0         |        0.0         |         0.0         |    446352748.0    |      2025-02-27 16:29:31      |  nan   |      nan      |  nan  |        1.0        |

Frequency Table for religion:
+---+----------+-------+
|   | religion | Count |
+---+----------+-------+
| 0 |    हिंदू    |  298  |
| 1 |   बौद्ध    |   4   |
| 2 |   मुस्लिम   |   1   |
+---+----------+-------+

Frequency Table for subcaste:
+----+------------+-------+
|    |  subcaste  | Count |
+----+------------+-------+
| 0  |    OBC     |  178  |
| 1  |    OPEN    |  22   |
| 2  |    VJNT    |  15   |
| 3  |     ST     |  14   |
| 4  |    NTC     |  12   |
| 5  |     SC     |  12   |
| 6  |     NT     |   9   |
| 7  |   कुणबीपाटील   |   9   |
| 8  |    SBC     |   8   |
| 9  |    मराठा     |   6   |
| 10 |   Kunbi    |   4   |
| 11 |     -      |   3   |
| 12 |    nan     |   3   |
| 13 |    NTB     |   2   |
| 14 | DhangarNTC |   1   |
| 15 |  हिंदूगोरबंजारा   |   1   |
| 16 |   NT(A)    |   1   |
| 17 |   NT(D)    |   1   |
| 18 |    बंजारा     |   1   |
| 19 |  General   |   1   |
+----+------------+-------+

Frequency Table for income_sources:
+----+---------------------------------------------+-------+
|    |               income_sources                | Count |
+----+---------------------------------------------+-------+
| 0  |             agriculture labour              |  195  |
| 1  |                 agriculture                 |  60   |
| 2  |                   labour                    |  18   |
| 3  |           agriculture Privatejob            |   8   |
| 4  |        agriculture labour Privatejob        |   5   |
| 5  |                labour Other                 |   2   |
| 6  |          agriculture labour Other           |   2   |
| 7  |              agriculture Other              |   2   |
| 8  |      agriculture labour GovernmentJob       |   1   |
| 9  |     agriculture business GovernmentJob      |   1   |
| 10 |         agriculture labour Pension          |   1   |
| 11 |        agriculture business Pension         |   1   |
| 12 |    agriculture Privatejob GovernmentJob     |   1   |
| 13 |     agriculture labour Privatejob Other     |   1   |
| 14 |                 Privatejob                  |   1   |
| 15 |         agriculture labour business         |   1   |
| 16 | agriculture labour Privatejob GovernmentJob |   1   |
| 17 |                    Other                    |   1   |
| 18 |            agriculture business             |   1   |
+----+---------------------------------------------+-------+

Frequency Table for bpl_status:
+---+------------+-------+
|   | bpl_status | Count |
+---+------------+-------+
| 0 |    yes     |  167  |
| 1 |     no     |  136  |
+---+------------+-------+

Frequency Table for ration_card:
+---+-------------+-------+
|   | ration_card | Count |
+---+-------------+-------+
| 0 |   orange    |  155  |
| 1 |   yellow    |  137  |
| 2 |    white    |   6   |
| 3 |    none     |   5   |
+---+-------------+-------+

Frequency Table for loan_status:
+---+-------------+-------+
|   | loan_status | Count |
+---+-------------+-------+
| 0 |     yes     |  267  |
| 1 |     no      |  36   |
+---+-------------+-------+

In [6]:
# Generate Pivot Tables for All Pairs of Categorical Variables
combos = list(combinations(categorical_vars, 2))
for var1, var2 in combos:
    print(f"\nPivot Table for {var1} vs {var2}:")
    pivot_table = pd.crosstab(survey_main[var1], survey_main[var2])
    print(tabulate(pivot_table, headers='keys', tablefmt='pretty'))
    
    # Heatmap visualization
    plt.figure(figsize=(10, 6))
    sns.heatmap(pivot_table, annot=True, fmt="d", cmap="coolwarm", linewidths=0.5)
    plt.title(f"Heatmap of {var1} vs {var2}")
    plt.xlabel(var2)
    plt.ylabel(var1)
    plt.savefig(os.path.join(output_dir, f"Heatmap_of_{var1}_vs_{var2}.jpg"))
    plt.close()

Pivot Table for gender vs marital_status:
+--------+---+----------+---------+-----------+
| gender | _ | divorced | married | unmarried |
+--------+---+----------+---------+-----------+
| female | 1 |    0     |    4    |     0     |
|  male  | 4 |    3     |   257   |    34     |
+--------+---+----------+---------+-----------+

Pivot Table for gender vs education:
+--------+----------+------------------+------------+---------+-----------+
| gender | graduate | higher_secondary | illiterate | primary | secondary |
+--------+----------+------------------+------------+---------+-----------+
| female |    0     |        0         |     0      |    3    |     2     |
|  male  |    17    |        48        |     44     |   95    |    94     |
+--------+----------+------------------+------------+---------+-----------+

Pivot Table for gender vs religion:
+--------+-----+------+-----+
| gender | बौद्ध | मुस्लिम | हिंदू  |
+--------+-----+------+-----+
| female |  0  |  0   |  5  |
|  male  |  4  |  1   | 293 |
+--------+-----+------+-----+

Pivot Table for gender vs subcaste:
+--------+---+------------+---------+-------+----+-------+-------+-----+-----+-----+------+-----+----+----+------+--------+-----+-----+---------+
| gender | - | DhangarNTC | General | Kunbi | NT | NT(A) | NT(D) | NTB | NTC | OBC | OPEN | SBC | SC | ST | VJNT | कुणबीपाटील | बंजारा | मराठा | हिंदूगोरबंजारा |
+--------+---+------------+---------+-------+----+-------+-------+-----+-----+-----+------+-----+----+----+------+--------+-----+-----+---------+
| female | 0 |     0      |    0    |   1   | 1  |   0   |   0   |  0  |  0  |  2  |  0   |  0  | 0  | 1  |  0   |   0    |  0  |  0  |    0    |
|  male  | 3 |     1      |    1    |   3   | 8  |   1   |   1   |  2  | 12  | 176 |  22  |  8  | 12 | 13 |  15  |   9    |  1  |  6  |    1    |
+--------+---+------------+---------+-------+----+-------+-------+-----+-----+-----+------+-----+----+----+------+--------+-----+-----+---------+

Pivot Table for gender vs income_sources:
+--------+-------+------------+-------------+-------------------+------------------------+--------------------------------------+----------------------+------------------------------------+------------------------------+--------------------+----------------------------------+--------------------------+----------------------------+-------------------------------+---------------------------------------------+-------------------------------------+-----------------------------+--------+--------------+
| gender | Other | Privatejob | agriculture | agriculture Other | agriculture Privatejob | agriculture Privatejob GovernmentJob | agriculture business | agriculture business GovernmentJob | agriculture business Pension | agriculture labour | agriculture labour GovernmentJob | agriculture labour Other | agriculture labour Pension | agriculture labour Privatejob | agriculture labour Privatejob GovernmentJob | agriculture labour Privatejob Other | agriculture labour business | labour | labour Other |
+--------+-------+------------+-------------+-------------------+------------------------+--------------------------------------+----------------------+------------------------------------+------------------------------+--------------------+----------------------------------+--------------------------+----------------------------+-------------------------------+---------------------------------------------+-------------------------------------+-----------------------------+--------+--------------+
| female |   0   |     0      |      1      |         0         |           1            |                  0                   |          0           |                 0                  |              0               |         3          |                0                 |            0             |             0              |               0               |                      0                      |                  0                  |              0              |   0    |      0       |
|  male  |   1   |     1      |     59      |         2         |           7            |                  1                   |          1           |                 1                  |              1               |        192         |                1                 |            2             |             1              |               5               |                      1                      |                  1                  |              1              |   18   |      2       |
+--------+-------+------------+-------------+-------------------+------------------------+--------------------------------------+----------------------+------------------------------------+------------------------------+--------------------+----------------------------------+--------------------------+----------------------------+-------------------------------+---------------------------------------------+-------------------------------------+-----------------------------+--------+--------------+

Pivot Table for gender vs bpl_status:
+--------+-----+-----+
| gender | no  | yes |
+--------+-----+-----+
| female |  3  |  2  |
|  male  | 133 | 165 |
+--------+-----+-----+

Pivot Table for gender vs ration_card:
+--------+------+--------+-------+--------+
| gender | none | orange | white | yellow |
+--------+------+--------+-------+--------+
| female |  0   |   4    |   0   |   1    |
|  male  |  5   |  151   |   6   |  136   |
+--------+------+--------+-------+--------+

Pivot Table for gender vs loan_status:
+--------+----+-----+
| gender | no | yes |
+--------+----+-----+
| female | 0  |  5  |
|  male  | 36 | 262 |
+--------+----+-----+

Pivot Table for marital_status vs education:
+----------------+----------+------------------+------------+---------+-----------+
| marital_status | graduate | higher_secondary | illiterate | primary | secondary |
+----------------+----------+------------------+------------+---------+-----------+
|       _        |    0     |        1         |     0      |    3    |     1     |
|    divorced    |    0     |        1         |     0      |    1    |     1     |
|    married     |    11    |        36        |     43     |   87    |    84     |
|   unmarried    |    6     |        10        |     1      |    7    |    10     |
+----------------+----------+------------------+------------+---------+-----------+

Pivot Table for marital_status vs religion:
+----------------+-----+------+-----+
| marital_status | बौद्ध | मुस्लिम | हिंदू  |
+----------------+-----+------+-----+
|       _        |  0  |  0   |  5  |
|    divorced    |  0  |  0   |  3  |
|    married     |  4  |  0   | 257 |
|   unmarried    |  0  |  1   | 33  |
+----------------+-----+------+-----+

Pivot Table for marital_status vs subcaste:
+----------------+---+------------+---------+-------+----+-------+-------+-----+-----+-----+------+-----+----+----+------+--------+-----+-----+---------+
| marital_status | - | DhangarNTC | General | Kunbi | NT | NT(A) | NT(D) | NTB | NTC | OBC | OPEN | SBC | SC | ST | VJNT | कुणबीपाटील | बंजारा | मराठा | हिंदूगोरबंजारा |
+----------------+---+------------+---------+-------+----+-------+-------+-----+-----+-----+------+-----+----+----+------+--------+-----+-----+---------+
|       _        | 0 |     0      |    0    |   0   | 0  |   0   |   0   |  0  |  1  |  4  |  0   |  0  | 0  | 0  |  0   |   0    |  0  |  0  |    0    |
|    divorced    | 0 |     0      |    0    |   0   | 0  |   0   |   0   |  0  |  0  |  3  |  0   |  0  | 0  | 0  |  0   |   0    |  0  |  0  |    0    |
|    married     | 2 |     1      |    0    |   4   | 8  |   1   |   1   |  2  | 10  | 149 |  21  |  7  | 12 | 11 |  13  |   8    |  1  |  6  |    1    |
|   unmarried    | 1 |     0      |    1    |   0   | 1  |   0   |   0   |  0  |  1  | 22  |  1   |  1  | 0  | 3  |  2   |   1    |  0  |  0  |    0    |
+----------------+---+------------+---------+-------+----+-------+-------+-----+-----+-----+------+-----+----+----+------+--------+-----+-----+---------+

Pivot Table for marital_status vs income_sources:
+----------------+-------+------------+-------------+-------------------+------------------------+--------------------------------------+----------------------+------------------------------------+------------------------------+--------------------+----------------------------------+--------------------------+----------------------------+-------------------------------+---------------------------------------------+-------------------------------------+-----------------------------+--------+--------------+
| marital_status | Other | Privatejob | agriculture | agriculture Other | agriculture Privatejob | agriculture Privatejob GovernmentJob | agriculture business | agriculture business GovernmentJob | agriculture business Pension | agriculture labour | agriculture labour GovernmentJob | agriculture labour Other | agriculture labour Pension | agriculture labour Privatejob | agriculture labour Privatejob GovernmentJob | agriculture labour Privatejob Other | agriculture labour business | labour | labour Other |
+----------------+-------+------------+-------------+-------------------+------------------------+--------------------------------------+----------------------+------------------------------------+------------------------------+--------------------+----------------------------------+--------------------------+----------------------------+-------------------------------+---------------------------------------------+-------------------------------------+-----------------------------+--------+--------------+
|       _        |   0   |     0      |      1      |         1         |           0            |                  0                   |          0           |                 0                  |              0               |         3          |                0                 |            0             |             0              |               0               |                      0                      |                  0                  |              0              |   0    |      0       |
|    divorced    |   0   |     0      |      0      |         0         |           0            |                  0                   |          0           |                 0                  |              0               |         3          |                0                 |            0             |             0              |               0               |                      0                      |                  0                  |              0              |   0    |      0       |
|    married     |   1   |     1      |     50      |         1         |           8            |                  1                   |          0           |                 0                  |              1               |        170         |                1                 |            2             |             0              |               5               |                      1                      |                  1                  |              1              |   15   |      2       |
|   unmarried    |   0   |     0      |      9      |         0         |           0            |                  0                   |          1           |                 1                  |              0               |         19         |                0                 |            0             |             1              |               0               |                      0                      |                  0                  |              0              |   3    |      0       |
+----------------+-------+------------+-------------+-------------------+------------------------+--------------------------------------+----------------------+------------------------------------+------------------------------+--------------------+----------------------------------+--------------------------+----------------------------+-------------------------------+---------------------------------------------+-------------------------------------+-----------------------------+--------+--------------+

Pivot Table for marital_status vs bpl_status:
+----------------+-----+-----+
| marital_status | no  | yes |
+----------------+-----+-----+
|       _        |  2  |  3  |
|    divorced    |  1  |  2  |
|    married     | 119 | 142 |
|   unmarried    | 14  | 20  |
+----------------+-----+-----+

Pivot Table for marital_status vs ration_card:
+----------------+------+--------+-------+--------+
| marital_status | none | orange | white | yellow |
+----------------+------+--------+-------+--------+
|       _        |  0   |   2    |   1   |   2    |
|    divorced    |  0   |   1    |   0   |   2    |
|    married     |  5   |  133   |   4   |  119   |
|   unmarried    |  0   |   19   |   1   |   14   |
+----------------+------+--------+-------+--------+

Pivot Table for marital_status vs loan_status:
+----------------+----+-----+
| marital_status | no | yes |
+----------------+----+-----+
|       _        | 1  |  4  |
|    divorced    | 0  |  3  |
|    married     | 31 | 230 |
|   unmarried    | 4  | 30  |
+----------------+----+-----+

Pivot Table for education vs religion:
+------------------+-----+------+----+
|    education     | बौद्ध | मुस्लिम | हिंदू |
+------------------+-----+------+----+
|     graduate     |  0  |  1   | 16 |
| higher_secondary |  0  |  0   | 48 |
|    illiterate    |  1  |  0   | 43 |
|     primary      |  2  |  0   | 96 |
|    secondary     |  1  |  0   | 95 |
+------------------+-----+------+----+

Pivot Table for education vs subcaste:
+------------------+---+------------+---------+-------+----+-------+-------+-----+-----+-----+------+-----+----+----+------+--------+-----+-----+---------+
|    education     | - | DhangarNTC | General | Kunbi | NT | NT(A) | NT(D) | NTB | NTC | OBC | OPEN | SBC | SC | ST | VJNT | कुणबीपाटील | बंजारा | मराठा | हिंदूगोरबंजारा |
+------------------+---+------------+---------+-------+----+-------+-------+-----+-----+-----+------+-----+----+----+------+--------+-----+-----+---------+
|     graduate     | 0 |     0      |    1    |   0   | 0  |   0   |   0   |  0  |  0  | 15  |  0   |  0  | 0  | 0  |  1   |   0    |  0  |  0  |    0    |
| higher_secondary | 2 |     0      |    0    |   2   | 0  |   0   |   0   |  0  |  0  | 33  |  4   |  1  | 2  | 1  |  1   |   2    |  0  |  0  |    0    |
|    illiterate    | 1 |     1      |    0    |   0   | 1  |   0   |   1   |  1  |  3  | 17  |  2   |  1  | 1  | 3  |  3   |   2    |  1  |  3  |    1    |
|     primary      | 0 |     0      |    0    |   1   | 2  |   1   |   0   |  0  |  8  | 57  |  7   |  5  | 5  | 6  |  3   |   3    |  0  |  0  |    0    |
|    secondary     | 0 |     0      |    0    |   1   | 6  |   0   |   0   |  1  |  1  | 56  |  9   |  1  | 4  | 4  |  7   |   2    |  0  |  3  |    0    |
+------------------+---+------------+---------+-------+----+-------+-------+-----+-----+-----+------+-----+----+----+------+--------+-----+-----+---------+

Pivot Table for education vs income_sources:
+------------------+-------+------------+-------------+-------------------+------------------------+--------------------------------------+----------------------+------------------------------------+------------------------------+--------------------+----------------------------------+--------------------------+----------------------------+-------------------------------+---------------------------------------------+-------------------------------------+-----------------------------+--------+--------------+
|    education     | Other | Privatejob | agriculture | agriculture Other | agriculture Privatejob | agriculture Privatejob GovernmentJob | agriculture business | agriculture business GovernmentJob | agriculture business Pension | agriculture labour | agriculture labour GovernmentJob | agriculture labour Other | agriculture labour Pension | agriculture labour Privatejob | agriculture labour Privatejob GovernmentJob | agriculture labour Privatejob Other | agriculture labour business | labour | labour Other |
+------------------+-------+------------+-------------+-------------------+------------------------+--------------------------------------+----------------------+------------------------------------+------------------------------+--------------------+----------------------------------+--------------------------+----------------------------+-------------------------------+---------------------------------------------+-------------------------------------+-----------------------------+--------+--------------+
|     graduate     |   0   |     0      |      3      |         0         |           0            |                  0                   |          0           |                 0                  |              0               |         12         |                0                 |            0             |             0              |               0               |                      0                      |                  0                  |              0              |   1    |      1       |
| higher_secondary |   0   |     0      |     14      |         0         |           1            |                  0                   |          1           |                 1                  |              0               |         25         |                0                 |            2             |             0              |               2               |                      0                      |                  0                  |              0              |   1    |      1       |
|    illiterate    |   0   |     0      |     11      |         1         |           0            |                  0                   |          0           |                 0                  |              0               |         28         |                0                 |            0             |             0              |               1               |                      0                      |                  0                  |              0              |   3    |      0       |
|     primary      |   1   |     0      |     16      |         1         |           4            |                  1                   |          0           |                 0                  |              0               |         65         |                1                 |            0             |             0              |               1               |                      1                      |                  1                  |              0              |   6    |      0       |
|    secondary     |   0   |     1      |     16      |         0         |           3            |                  0                   |          0           |                 0                  |              1               |         65         |                0                 |            0             |             1              |               1               |                      0                      |                  0                  |              1              |   7    |      0       |
+------------------+-------+------------+-------------+-------------------+------------------------+--------------------------------------+----------------------+------------------------------------+------------------------------+--------------------+----------------------------------+--------------------------+----------------------------+-------------------------------+---------------------------------------------+-------------------------------------+-----------------------------+--------+--------------+

Pivot Table for education vs bpl_status:
+------------------+----+-----+
|    education     | no | yes |
+------------------+----+-----+
|     graduate     | 9  |  8  |
| higher_secondary | 29 | 19  |

Pivot Table for marital_status vs bpl_status:
+----------------+-----+-----+
| marital_status | no  | yes |
+----------------+-----+-----+
|    divorced    |  1  |  2  |
|    married     | 121 | 144 |
|   unmarried    | 14  | 21  |
+----------------+-----+-----+

Pivot Table for marital_status vs ration_card:
+----------------+------+--------+-------+--------+
| marital_status | none | orange | white | yellow |
+----------------+------+--------+-------+--------+
|    divorced    |  0   |   1    |   0   |   2    |
|    married     |  5   |  134   |   5   |  121   |
|   unmarried    |  0   |   20   |   1   |   14   |
+----------------+------+--------+-------+--------+

Pivot Table for marital_status vs loan_status:
+----------------+----+-----+
| marital_status | no | yes |
+----------------+----+-----+
|    divorced    | 0  |  3  |
|    married     | 32 | 233 |
|   unmarried    | 4  | 31  |
+----------------+----+-----+

Pivot Table for education vs religion:
+------------------+-----+------+----+
|    education     | बौद्ध | मुस्लिम | हिंदू |
+------------------+-----+------+----+
|     graduate     |  0  |  1   | 16 |
| higher_secondary |  0  |  0   | 48 |
|    illiterate    |  1  |  0   | 43 |
|     primary      |  2  |  0   | 96 |
|    secondary     |  1  |  0   | 95 |
+------------------+-----+------+----+

Pivot Table for education vs subcaste:
+------------------+---+------------+---------+-------+----+-------+-------+-----+-----+-----+------+-----+----+----+------+--------+-----+-----+---------+
|    education     | - | DhangarNTC | General | Kunbi | NT | NT(A) | NT(D) | NTB | NTC | OBC | OPEN | SBC | SC | ST | VJNT | कुणबीपाटील | बंजारा | मराठा | हिंदूगोरबंजारा |
+------------------+---+------------+---------+-------+----+-------+-------+-----+-----+-----+------+-----+----+----+------+--------+-----+-----+---------+
|     graduate     | 0 |     0      |    1    |   0   | 0  |   0   |   0   |  0  |  0  | 15  |  0   |  0  | 0  | 0  |  1   |   0    |  0  |  0  |    0    |
| higher_secondary | 2 |     0      |    0    |   2   | 0  |   0   |   0   |  0  |  0  | 33  |  4   |  1  | 2  | 1  |  1   |   2    |  0  |  0  |    0    |
|    illiterate    | 1 |     1      |    0    |   0   | 1  |   0   |   1   |  1  |  3  | 17  |  2   |  1  | 1  | 3  |  3   |   2    |  1  |  3  |    1    |
|     primary      | 0 |     0      |    0    |   1   | 2  |   1   |   0   |  0  |  8  | 57  |  7   |  5  | 5  | 6  |  3   |   3    |  0  |  0  |    0    |
|    secondary     | 0 |     0      |    0    |   1   | 6  |   0   |   0   |  1  |  1  | 56  |  9   |  1  | 4  | 4  |  7   |   2    |  0  |  3  |    0    |
+------------------+---+------------+---------+-------+----+-------+-------+-----+-----+-----+------+-----+----+----+------+--------+-----+-----+---------+

Pivot Table for education vs income_sources:
+------------------+-------+------------+-------------+-------------------+------------------------+--------------------------------------+----------------------+------------------------------------+------------------------------+--------------------+----------------------------------+--------------------------+----------------------------+-------------------------------+---------------------------------------------+-------------------------------------+-----------------------------+--------+--------------+
|    education     | Other | Privatejob | agriculture | agriculture Other | agriculture Privatejob | agriculture Privatejob GovernmentJob | agriculture business | agriculture business GovernmentJob | agriculture business Pension | agriculture labour | agriculture labour GovernmentJob | agriculture labour Other | agriculture labour Pension | agriculture labour Privatejob | agriculture labour Privatejob GovernmentJob | agriculture labour Privatejob Other | agriculture labour business | labour | labour Other |
+------------------+-------+------------+-------------+-------------------+------------------------+--------------------------------------+----------------------+------------------------------------+------------------------------+--------------------+----------------------------------+--------------------------+----------------------------+-------------------------------+---------------------------------------------+-------------------------------------+-----------------------------+--------+--------------+
|     graduate     |   0   |     0      |      3      |         0         |           0            |                  0                   |          0           |                 0                  |              0               |         12         |                0                 |            0             |             0              |               0               |                      0                      |                  0                  |              0              |   1    |      1       |
| higher_secondary |   0   |     0      |     14      |         0         |           1            |                  0                   |          1           |                 1                  |              0               |         25         |                0                 |            2             |             0              |               2               |                      0                      |                  0                  |              0              |   1    |      1       |
|    illiterate    |   0   |     0      |     11      |         1         |           0            |                  0                   |          0           |                 0                  |              0               |         28         |                0                 |            0             |             0              |               1               |                      0                      |                  0                  |              0              |   3    |      0       |
|     primary      |   1   |     0      |     16      |         1         |           4            |                  1                   |          0           |                 0                  |              0               |         65         |                1                 |            0             |             0              |               1               |                      1                      |                  1                  |              0              |   6    |      0       |
|    secondary     |   0   |     1      |     16      |         0         |           3            |                  0                   |          0           |                 0                  |              1               |         65         |                0                 |            0             |             1              |               1               |                      0                      |                  0                  |              1              |   7    |      0       |
+------------------+-------+------------+-------------+-------------------+------------------------+--------------------------------------+----------------------+------------------------------------+------------------------------+--------------------+----------------------------------+--------------------------+----------------------------+-------------------------------+---------------------------------------------+-------------------------------------+-----------------------------+--------+--------------+

Pivot Table for education vs bpl_status:
+------------------+----+-----+
|    education     | no | yes |
+------------------+----+-----+
|     graduate     | 9  |  8  |
| higher_secondary | 29 | 19  |
|    illiterate    | 13 | 31  |
|     primary      | 42 | 56  |
|    secondary     | 43 | 53  |
+------------------+----+-----+

Pivot Table for education vs ration_card:
+------------------+------+--------+-------+--------+
|    education     | none | orange | white | yellow |
+------------------+------+--------+-------+--------+
|     graduate     |  0   |   13   |   0   |   4    |
| higher_secondary |  1   |   33   |   1   |   13   |
|    illiterate    |  1   |   18   |   1   |   24   |
|     primary      |  2   |   40   |   2   |   54   |
|    secondary     |  1   |   51   |   2   |   42   |
+------------------+------+--------+-------+--------+

Pivot Table for education vs loan_status:
+------------------+----+-----+
|    education     | no | yes |
+------------------+----+-----+
|     graduate     | 1  | 16  |
| higher_secondary | 5  | 43  |
|    illiterate    | 4  | 40  |
|     primary      | 18 | 80  |
|    secondary     | 8  | 88  |
+------------------+----+-----+

Pivot Table for religion vs subcaste:
+----------+---+------------+---------+-------+----+-------+-------+-----+-----+-----+------+-----+----+----+------+--------+-----+-----+---------+
| religion | - | DhangarNTC | General | Kunbi | NT | NT(A) | NT(D) | NTB | NTC | OBC | OPEN | SBC | SC | ST | VJNT | कुणबीपाटील | बंजारा | मराठा | हिंदूगोरबंजारा |
+----------+---+------------+---------+-------+----+-------+-------+-----+-----+-----+------+-----+----+----+------+--------+-----+-----+---------+
|   बौद्ध    | 0 |     0      |    0    |   0   | 0  |   0   |   0   |  0  |  0  |  0  |  0   |  0  | 4  | 0  |  0   |   0    |  0  |  0  |    0    |
|   मुस्लिम   | 0 |     0      |    1    |   0   | 0  |   0   |   0   |  0  |  0  |  0  |  0   |  0  | 0  | 0  |  0   |   0    |  0  |  0  |    0    |
|    हिंदू    | 3 |     1      |    0    |   4   | 9  |   1   |   1   |  2  | 12  | 178 |  22  |  8  | 8  | 14 |  15  |   9    |  1  |  6  |    1    |
+----------+---+------------+---------+-------+----+-------+-------+-----+-----+-----+------+-----+----+----+------+--------+-----+-----+---------+

Pivot Table for religion vs income_sources:
+----------+-------+------------+-------------+-------------------+------------------------+--------------------------------------+----------------------+------------------------------------+------------------------------+--------------------+----------------------------------+--------------------------+----------------------------+-------------------------------+---------------------------------------------+-------------------------------------+-----------------------------+--------+--------------+
| religion | Other | Privatejob | agriculture | agriculture Other | agriculture Privatejob | agriculture Privatejob GovernmentJob | agriculture business | agriculture business GovernmentJob | agriculture business Pension | agriculture labour | agriculture labour GovernmentJob | agriculture labour Other | agriculture labour Pension | agriculture labour Privatejob | agriculture labour Privatejob GovernmentJob | agriculture labour Privatejob Other | agriculture labour business | labour | labour Other |
+----------+-------+------------+-------------+-------------------+------------------------+--------------------------------------+----------------------+------------------------------------+------------------------------+--------------------+----------------------------------+--------------------------+----------------------------+-------------------------------+---------------------------------------------+-------------------------------------+-----------------------------+--------+--------------+
|   बौद्ध    |   0   |     0      |      0      |         0         |           0            |                  0                   |          0           |                 0                  |              0               |         4          |                0                 |            0             |             0              |               0               |                      0                      |                  0                  |              0              |   0    |      0       |
|   मुस्लिम   |   0   |     0      |      1      |         0         |           0            |                  0                   |          0           |                 0                  |              0               |         0          |                0                 |            0             |             0              |               0               |                      0                      |                  0                  |              0              |   0    |      0       |
|    हिंदू    |   1   |     1      |     59      |         2         |           8            |                  1                   |          1           |                 1                  |              1               |        191         |                1                 |            2             |             1              |               5               |                      1                      |                  1                  |              1              |   18   |      2       |
+----------+-------+------------+-------------+-------------------+------------------------+--------------------------------------+----------------------+------------------------------------+------------------------------+--------------------+----------------------------------+--------------------------+----------------------------+-------------------------------+---------------------------------------------+-------------------------------------+-----------------------------+--------+--------------+

Pivot Table for religion vs bpl_status:
+----------+-----+-----+
| religion | no  | yes |
+----------+-----+-----+
|   बौद्ध    |  1  |  3  |
|   मुस्लिम   |  1  |  0  |
|    हिंदू    | 134 | 164 |
+----------+-----+-----+

Pivot Table for religion vs ration_card:
+----------+------+--------+-------+--------+
| religion | none | orange | white | yellow |
+----------+------+--------+-------+--------+
|   बौद्ध    |  0   |   1    |   0   |   3    |
|   मुस्लिम   |  0   |   1    |   0   |   0    |
|    हिंदू    |  5   |  153   |   6   |  134   |
+----------+------+--------+-------+--------+

Pivot Table for religion vs loan_status:
+----------+----+-----+
| religion | no | yes |
+----------+----+-----+
|   बौद्ध    | 0  |  4  |
|   मुस्लिम   | 0  |  1  |
|    हिंदू    | 36 | 262 |
+----------+----+-----+

Pivot Table for subcaste vs income_sources:
+------------+-------+------------+-------------+-------------------+------------------------+--------------------------------------+----------------------+------------------------------------+------------------------------+--------------------+----------------------------------+--------------------------+----------------------------+-------------------------------+---------------------------------------------+-------------------------------------+-----------------------------+--------+--------------+
|  subcaste  | Other | Privatejob | agriculture | agriculture Other | agriculture Privatejob | agriculture Privatejob GovernmentJob | agriculture business | agriculture business GovernmentJob | agriculture business Pension | agriculture labour | agriculture labour GovernmentJob | agriculture labour Other | agriculture labour Pension | agriculture labour Privatejob | agriculture labour Privatejob GovernmentJob | agriculture labour Privatejob Other | agriculture labour business | labour | labour Other |
+------------+-------+------------+-------------+-------------------+------------------------+--------------------------------------+----------------------+------------------------------------+------------------------------+--------------------+----------------------------------+--------------------------+----------------------------+-------------------------------+---------------------------------------------+-------------------------------------+-----------------------------+--------+--------------+
|     -      |   0   |     0      |      0      |         0         |           0            |                  0                   |          0           |                 0                  |              0               |         3          |                0                 |            0             |             0              |               0               |                      0                      |                  0                  |              0              |   0    |      0       |
| DhangarNTC |   0   |     0      |      0      |         0         |           0            |                  0                   |          0           |                 0                  |              0               |         1          |                0                 |            0             |             0              |               0               |                      0                      |                  0                  |              0              |   0    |      0       |
|  General   |   0   |     0      |      1      |         0         |           0            |                  0                   |          0           |                 0                  |              0               |         0          |                0                 |            0             |             0              |               0               |                      0                      |                  0                  |              0              |   0    |      0       |
|   Kunbi    |   0   |     0      |      0      |         0         |           1            |                  0                   |          0           |                 0                  |              0               |         3          |                0                 |            0             |             0              |               0               |                      0                      |                  0                  |              0              |   0    |      0       |
|     NT     |   0   |     0      |      1      |         0         |           0            |                  0                   |          0           |                 0                  |              0               |         7          |                0                 |            0             |             1              |               0               |                      0                      |                  0                  |              0              |   0    |      0       |
|   NT(A)    |   0   |     0      |      0      |         0         |           0            |                  0                   |          0           |                 0                  |              0               |         1          |                0                 |            0             |             0              |               0               |                      0                      |                  0                  |              0              |   0    |      0       |
|   NT(D)    |   0   |     0      |      0      |         0         |           0            |                  0                   |          0           |                 0                  |              0               |         1          |                0                 |            0             |             0              |               0               |                      0                      |                  0                  |              0              |   0    |      0       |
|    NTB     |   0   |     0      |      0      |         0         |           0            |                  0                   |          0           |                 0                  |              0               |         2          |                0                 |            0             |             0              |               0               |                      0                      |                  0                  |              0              |   0    |      0       |
|    NTC     |   0   |     0      |      4      |         1         |           0            |                  0                   |          0           |                 0                  |              1               |         6          |                0                 |            0             |             0              |               0               |                      0                      |                  0                  |              0              |   0    |      0       |
|    OBC     |   1   |     1      |     33      |         0         |           5            |                  1                   |          0           |                 1                  |              0               |        118         |                1                 |            1             |             0              |               5               |                      0                      |                  1                  |              0              |   9    |      1       |
|    OPEN    |   0   |     0      |      3      |         1         |           0            |                  0                   |          1           |                 0                  |              0               |         15         |                0                 |            1             |             0              |               0               |                      0                      |                  0                  |              0              |   1    |      0       |
|    SBC     |   0   |     0      |      4      |         0         |           0            |                  0                   |          0           |                 0                  |              0               |         4          |                0                 |            0             |             0              |               0               |                      0                      |                  0                  |              0              |   0    |      0       |
|     SC     |   0   |     0      |      0      |         0         |           0            |                  0                   |          0           |                 0                  |              0               |         8          |                0                 |            0             |             0              |               0               |                      1                      |                  0                  |              0              |   2    |      1       |
|     ST     |   0   |     0      |      2      |         0         |           0            |                  0                   |          0           |                 0                  |              0               |         8          |                0                 |            0             |             0              |               0               |                      0                      |                  0                  |              0              |   4    |      0       |
|    VJNT    |   0   |     0      |      2      |         0         |           2            |                  0                   |          0           |                 0                  |              0               |         9          |                0                 |            0             |             0              |               0               |                      0                      |                  0                  |              0              |   2    |      0       |
|   कुणबीपाटील   |   0   |     0      |      3      |         0         |           0            |                  0                   |          0           |                 0                  |              0               |         5          |                0                 |            0             |             0              |               0               |                      0                      |                  0                  |              1              |   0    |      0       |
|    बंजारा     |   0   |     0      |      1      |         0         |           0            |                  0                   |          0           |                 0                  |              0               |         0          |                0                 |            0             |             0              |               0               |                      0                      |                  0                  |              0              |   0    |      0       |
|    मराठा     |   0   |     0      |      6      |         0         |           0            |                  0                   |          0           |                 0                  |              0               |         0          |                0                 |            0             |             0              |               0               |                      0                      |                  0                  |              0              |   0    |      0       |
|  हिंदूगोरबंजारा   |   0   |     0      |      0      |         0         |           0            |                  0                   |          0           |                 0                  |              0               |         1          |                0                 |            0             |             0              |               0               |                      0                      |                  0                  |              0              |   0    |      0       |
+------------+-------+------------+-------------+-------------------+------------------------+--------------------------------------+----------------------+------------------------------------+------------------------------+--------------------+----------------------------------+--------------------------+----------------------------+-------------------------------+---------------------------------------------+-------------------------------------+-----------------------------+--------+--------------+

Pivot Table for subcaste vs bpl_status:
+------------+----+-----+
|  subcaste  | no | yes |
+------------+----+-----+
|     -      | 3  |  0  |
| DhangarNTC | 0  |  1  |
|  General   | 1  |  0  |
|   Kunbi    | 0  |  4  |
|     NT     | 5  |  4  |
|   NT(A)    | 1  |  0  |
|   NT(D)    | 0  |  1  |
|    NTB     | 2  |  0  |
|    NTC     | 7  |  5  |
|    OBC     | 82 | 96  |
|    OPEN    | 12 | 10  |
|    SBC     | 4  |  4  |
|     SC     | 4  |  8  |
|     ST     | 3  | 11  |
|    VJNT    | 6  |  9  |
|   कुणबीपाटील   | 4  |  5  |
|    बंजारा     | 0  |  1  |
|    मराठा     | 0  |  6  |
|  हिंदूगोरबंजारा   | 0  |  1  |
+------------+----+-----+

Pivot Table for subcaste vs ration_card:
+------------+------+--------+-------+--------+
|  subcaste  | none | orange | white | yellow |
+------------+------+--------+-------+--------+
|     -      |  0   |   3    |   0   |   0    |
| DhangarNTC |  0   |   1    |   0   |   0    |
|  General   |  0   |   1    |   0   |   0    |
|   Kunbi    |  0   |   3    |   0   |   1    |
|     NT     |  0   |   6    |   0   |   3    |
|   NT(A)    |  0   |   0    |   0   |   1    |
|   NT(D)    |  0   |   0    |   0   |   1    |
|    NTB     |  0   |   2    |   0   |   0    |
|    NTC     |  0   |   7    |   0   |   5    |
|    OBC     |  3   |   93   |   2   |   80   |
|    OPEN    |  2   |   11   |   0   |   9    |
|    SBC     |  0   |   3    |   1   |   4    |
|     SC     |  0   |   5    |   1   |   6    |
|     ST     |  0   |   3    |   0   |   11   |
|    VJNT    |  0   |   7    |   2   |   6    |
|   कुणबीपाटील   |  0   |   5    |   0   |   4    |
|    बंजारा     |  0   |   1    |   0   |   0    |
|    मराठा     |  0   |   2    |   0   |   4    |
|  हिंदूगोरबंजारा   |  0   |   0    |   0   |   1    |
+------------+------+--------+-------+--------+

Pivot Table for subcaste vs loan_status:
+------------+----+-----+
|  subcaste  | no | yes |
+------------+----+-----+
|     -      | 1  |  2  |
| DhangarNTC | 1  |  0  |
|  General   | 0  |  1  |
|   Kunbi    | 0  |  4  |
|     NT     | 0  |  9  |
|   NT(A)    | 0  |  1  |
|   NT(D)    | 0  |  1  |
|    NTB     | 0  |  2  |
|    NTC     | 3  |  9  |
|    OBC     | 21 | 157 |
|    OPEN    | 0  | 22  |
|    SBC     | 3  |  5  |
|     SC     | 3  |  9  |
|     ST     | 3  | 11  |
|    VJNT    | 0  | 15  |
|   कुणबीपाटील   | 1  |  8  |
|    बंजारा     | 0  |  1  |
|    मराठा     | 0  |  6  |
|  हिंदूगोरबंजारा   | 0  |  1  |
+------------+----+-----+

Pivot Table for income_sources vs bpl_status:
+---------------------------------------------+----+-----+
|               income_sources                | no | yes |
+---------------------------------------------+----+-----+
|                    Other                    | 1  |  0  |
|                 Privatejob                  | 0  |  1  |
|                 agriculture                 | 31 | 29  |
|              agriculture Other              | 0  |  2  |
|           agriculture Privatejob            | 3  |  5  |
|    agriculture Privatejob GovernmentJob     | 0  |  1  |
|            agriculture business             | 1  |  0  |
|     agriculture business GovernmentJob      | 1  |  0  |
|        agriculture business Pension         | 0  |  1  |
|             agriculture labour              | 86 | 109 |
|      agriculture labour GovernmentJob       | 1  |  0  |
|          agriculture labour Other           | 0  |  2  |
|         agriculture labour Pension          | 1  |  0  |
|        agriculture labour Privatejob        | 2  |  3  |
| agriculture labour Privatejob GovernmentJob | 1  |  0  |
|     agriculture labour Privatejob Other     | 0  |  1  |
|         agriculture labour business         | 1  |  0  |
|                   labour                    | 6  | 12  |
|                labour Other                 | 1  |  1  |
+---------------------------------------------+----+-----+

Pivot Table for income_sources vs ration_card:
+---------------------------------------------+------+--------+-------+--------+
|               income_sources                | none | orange | white | yellow |
+---------------------------------------------+------+--------+-------+--------+
|                    Other                    |  0   |   1    |   0   |   0    |
|                 Privatejob                  |  0   |   0    |   0   |   1    |
|                 agriculture                 |  1   |   37   |   0   |   22   |
|              agriculture Other              |  0   |   0    |   0   |   2    |
|           agriculture Privatejob            |  0   |   5    |   0   |   3    |
|    agriculture Privatejob GovernmentJob     |  0   |   0    |   0   |   1    |
|            agriculture business             |  0   |   1    |   0   |   0    |
|     agriculture business GovernmentJob      |  0   |   0    |   1   |   0    |
|        agriculture business Pension         |  0   |   0    |   0   |   1    |
|             agriculture labour              |  3   |   98   |   4   |   90   |
|      agriculture labour GovernmentJob       |  0   |   1    |   0   |   0    |
|          agriculture labour Other           |  0   |   0    |   0   |   2    |
|         agriculture labour Pension          |  0   |   1    |   0   |   0    |
|        agriculture labour Privatejob        |  0   |   1    |   0   |   4    |
| agriculture labour Privatejob GovernmentJob |  0   |   0    |   1   |   0    |
|     agriculture labour Privatejob Other     |  0   |   0    |   0   |   1    |
|         agriculture labour business         |  0   |   1    |   0   |   0    |
|                   labour                    |  1   |   7    |   0   |   10   |
|                labour Other                 |  0   |   2    |   0   |   0    |
+---------------------------------------------+------+--------+-------+--------+

Pivot Table for income_sources vs loan_status:
+---------------------------------------------+----+-----+
|               income_sources                | no | yes |
+---------------------------------------------+----+-----+
|                    Other                    | 0  |  1  |
|                 Privatejob                  | 1  |  0  |
|                 agriculture                 | 5  | 55  |
|              agriculture Other              | 1  |  1  |
|           agriculture Privatejob            | 1  |  7  |
|    agriculture Privatejob GovernmentJob     | 1  |  0  |
|            agriculture business             | 0  |  1  |
|     agriculture business GovernmentJob      | 0  |  1  |
|        agriculture business Pension         | 0  |  1  |
|             agriculture labour              | 20 | 175 |
|      agriculture labour GovernmentJob       | 0  |  1  |
|          agriculture labour Other           | 0  |  2  |
|         agriculture labour Pension          | 0  |  1  |
|        agriculture labour Privatejob        | 1  |  4  |
| agriculture labour Privatejob GovernmentJob | 1  |  0  |
|     agriculture labour Privatejob Other     | 0  |  1  |
|         agriculture labour business         | 0  |  1  |
|                   labour                    | 4  | 14  |
|                labour Other                 | 1  |  1  |
+---------------------------------------------+----+-----+

Pivot Table for bpl_status vs ration_card:
+------------+------+--------+-------+--------+
| bpl_status | none | orange | white | yellow |
+------------+------+--------+-------+--------+
|     no     |  3   |  117   |   5   |   11   |
|    yes     |  2   |   38   |   1   |  126   |
+------------+------+--------+-------+--------+

Pivot Table for bpl_status vs loan_status:
+------------+----+-----+
| bpl_status | no | yes |
+------------+----+-----+
|     no     | 16 | 120 |
|    yes     | 20 | 147 |
+------------+----+-----+

Pivot Table for ration_card vs loan_status:
+-------------+----+-----+
| ration_card | no | yes |
+-------------+----+-----+
|    none     | 1  |  4  |
|   orange    | 14 | 141 |
|    white    | 1  |  5  |
|   yellow    | 20 | 117 |
+-------------+----+-----+

In [7]:
#pd.pivot_table(
#    survey_main, 
#    values='column_to_aggregate', 
#    index='column_to_group_by', 
#    columns='column_to_pivot', 
#    aggfunc='function')

In [8]:
pd.pivot_table(
    survey_main, 
    values=['farmers_name'], 
    index='taluka', 
    columns='gender', 
    aggfunc='count',fill_value= 0)

           farmers_name
gender           female male
taluka
अमळनेर                0    8
एरंडोल                0   16
चाळीसगाव              0   27
चोपडा                 0   22
जळगाव                 1   24
जामनेर                1   60
धरणगाव                1   31
पाचोरा                1   14
पारोळा                1   39
बोदवड                 0   10
भडगाव                 0   15
भुसावळ                0    2
मुक्ताईनगर            0   20
यावल                  0    5
रावेर                 0    5

In [9]:
pd.pivot_table(
    survey_main, 
    values=['age'], 
    index='taluka', 
    columns='marital_status', 
    aggfunc='mean',fill_value= 0)

                 age
marital_status     _ divorced    married  unmarried
taluka
अमळनेर           0.0      0.0  55.000000   0.000000
एरंडोल           0.0     30.0  52.076923  24.000000
चाळीसगाव        59.0      0.0  45.208333  27.500000
चोपडा            0.0     35.0  45.777778  27.000000
जळगाव            0.0      0.0  48.416667  27.000000
जामनेर          38.0      0.0  42.400000  30.600000
धरणगाव           0.0      0.0  51.107143  29.750000
पाचोरा           0.0      0.0  41.538462  29.000000
पारोळा          43.5     37.0  45.636364  27.000000
बोदवड           65.0      0.0  50.777778   0.000000
भडगाव            0.0      0.0  48.333333  33.666667
भुसावळ           0.0      0.0  43.000000   0.000000
मुक्ताईनगर       0.0      0.0  43.764706  29.333333
यावल             0.0      0.0  48.200000   0.000000
रावेर            0.0      0.0  53.200000   0.000000

In [20]:
survey_main.depression_1

0       often
1      rarely
2      rarely
3      rarely
4      rarely
        ...
298     never
299    rarely
300    always
301    rarely
302    rarely
Name: depression_1, Length: 303, dtype: object